name: scanpy-pbmc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - jupyter
  - notebook
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pip:
      - scanpy[leiden]
      - anndata
      - leidenalg
      - python-igraph
      - louvain
      - umap-learn
